rust:
- src/**/*.rs

collector:
- src/collectors/**/*

network-collector:
- src/collectors/network_collector.rs

system-collector:
- src/collectors/dmi_collector.rs

configuration:
- src/configuration/**/*.rs

publisher:
- src/publisher/*

api-client:
- src/publisher/api_client/*

dependencies:
- Cargo.toml
- Cargo.lock

documentation:
- README.md
- LICENSE
- CODE_OF_CONDUCT.md
- CONTRIBUTING

tests:
- tests/*

code-quality:
- .pre-commit-hooks/*
- .pre-commit-config.yaml

maintenance:
- .github/*